spring.application.name=Squadly

spring.datasource.url=jdbc:postgresql://localhost:5432/squadly_db
spring.datasource.username=squadly_db_user
spring.datasource.password=squadlydbuser
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

